### ISSUE TITLE
[Bug] - AttributeError: partially initialized module 'streamlit' has no attribute 'set_page_config' (most likely due to a circular import)

### ISSUE THREAD

**Issue by David-GERARD** [streamlit/streamlit-app-action#8]
Dear Streamlit team,

I have encountered a similar bug as found in  hwchase17/conversational-retrieval-agent#1 when running the following job:

```yaml
check-gui:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu"]
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: daps-hackathon
        auto-activate-base: false

    - uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: streamlit.py
        ruff: false
```

The error log is: 

```bash
==================================== ERRORS ====================================
______________________ ERROR collecting st_smoke_test.py _______________________
st_smoke_test.py:5: in <module>
    from streamlit.testing.v1 import AppTest
streamlit.py:4: in <module>
    st.set_page_config(layout="wide")
E   AttributeError: partially initialized module 'streamlit' has no attribute 'set_page_config' (most likely due to a circular import)
=========================== short test summary info ============================
ERROR st_smoke_test.py - AttributeError: partially initialized module 'streamlit' has no attribute 'set_page_config' (most likely due to a circular import)
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.09s ===============================

```
